# Generated by Django 5.2 on 2025-06-10 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_gigfaq_giggallery_gigpackage_savedgig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giggallery',
            name='media_url',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='giggallery',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='gig_gallery/'),
        ),
        migrations.AddField(
            model_name='gigpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='savedgig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='gig_thumbnails/'),
        ),
        migrations.AlterUniqueTogether(
            name='savedgig',
            unique_together={('user', 'gig')},
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['category'], name='gigs_gig_categor_a1ad8d_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['subcategory'], name='gigs_gig_subcate_fe5fae_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['seller'], name='gigs_gig_seller__5defcc_idx'),
        ),
    ]
