# Generated by Django 5.2 on 2025-06-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
        ('gigs', '0003_remove_giggallery_media_url_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='accounts.sellerprofile'),
        ),
    ]
